In [ ]:
import numpy as np


In [3]:
arr = np.array([10,20,30,40,50])
print(arr)



[10 20 30 40 50]


In [5]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.ones(10)
arr



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
arr = np.arange(5,51,5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [14]:
arr = np.arange(1,10).reshape(3,3)

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])


In [18]:
arr.ndim



2

In [ ]:
arr.shape


(2, 3)

In [ ]:
arr.size


6

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr.nbytes

48

In [28]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:

arr[4,4]
arr[0]
arr[1:4,1:4]
arr.T


array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [34]:
sales = np.array([100, 200, 150, 300, 250])


In [42]:
sales.sum()
sales.mean()
sales.max()
sales.min()
sales=sales*10
sales
sales = sales*0.15
sales


array([1500., 3000., 2250., 4500., 3750.])

In [ ]:
scores = np.array([55, 67, 72, 89, 91, 45, 78, 88, 95, 60])
scores.mean()
np.median(scores)
np.std(scores)
np.var(scores)
np.max(scores)
np.min(scores)
np.percentile(scores,25)
np.precentitle(scores,50)


AttributeError: module 'numpy' has no attribute 'precentitle'