In [1]:
import numpy as np


In [2]:
ages = np.array([18, 22, 35, 17, 40, 28, 15, 31])

In [7]:
age = ages>18
ages[age]


array([22, 35, 40, 28, 31])

In [23]:
ages[ages<18]
ages[(ages>20)&(ages<35)]
ages[ages>25].size
ages




array([18, 22, 35,  0, 40, 28,  0, 31])


Exercise 7
arr = np.arange(1, 25)

Convert it into:

2×12
3×8
4×6
6×4
8×3
12×2


Then flatten it back to one dimension.



In [26]:
arr=np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(3,8)
arr.flatten()


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])