Valid Sudoku



In [ ]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])



In [38]:
# np.sum(s,axis=1)
# np.sum(s,axis=0)
s[0:3,0:3].sum()
s[0:3,3:6]
s[0:3,6:9]

s[3:6,0:3]
s[3:6,3:6]
s[3:6,6:9]

for i in range(0,10,3):
    for j in range(0,10,3):
            print(s[j:j+3,i:i+3])
            print(s[j:j+3,i:i+3].sum())

            print(" ")



[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
 
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
 
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
 
[]
0
 
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
 
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
 
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
 
[]
0
 
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
 
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
 
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45
 
[]
0
 
[]
0
 
[]
0
 
[]
0
 
[]
0
 
